feat: support v21 and drop v8 (#64)
* feat: support v21 and drop v8

* fix: add --ignore-missing-links to ignore failure

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* fix: ignore failure on windows for v21

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,9 +20,11 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        clang-version: [ 20, 19, 18, 17, 16, 15, 14, 13, 12.0.1, 12, 11, 10, 9, 8]
+        clang-version: [ 21, 20, 19, 18, 17, 16, 15, 14, 13, 12.0.1, 12, 11, 10, 9]
         os: [ linux, macosx, windows ]
         include:
+          - clang-version: 21
+            release: llvm-project-21.1.0.src
           - clang-version: 20
             release: llvm-project-20.1.0.src
           - clang-version: 19
@@ -51,9 +53,6 @@ jobs:
           - clang-version: 9
             release: llvm-project-9.0.1
             extra-cmake-args: '-DLLVM_ENABLE_Z3_SOLVER=OFF'
-          - clang-version: 8
-            release: llvm-project-8.0.1
-            extra-cmake-args: '-DCLANG_ANALYZER_ENABLE_Z3_SOLVER=OFF'
           - os: linux
             runner: ubuntu-22.04
             os-cmake-args: '-DLLVM_BUILD_STATIC=ON -DCMAKE_CXX_FLAGS="-s -flto" ${POSIX_CMAKE_ARGS} ${LINUX_CMAKE_ARGS}'
@@ -92,41 +91,16 @@ jobs:
       shell: bash
       run: curl -L https://github.com/${{ github.repository }}/archive/${{ github.ref }}.tar.gz | tar xvz --strip 1
     - name: Get llvm-project
-      if: ${{ matrix.clang-version == 8 }}
-      shell: bash
-      run: |
-        version=${RELEASE##llvm-project-}
-        curl -LO https://github.com/llvm/llvm-project/releases/download/llvmorg-${version}/llvm-${version}.src.tar.xz
-        curl -LO https://github.com/llvm/llvm-project/releases/download/llvmorg-${version}/cfe-${version}.src.tar.xz
-        curl -LO https://github.com/llvm/llvm-project/releases/download/llvmorg-${version}/clang-tools-extra-${version}.src.tar.xz
-    - name: Get llvm-project
       if: ${{ matrix.clang-version >= 9 || matrix.clang-version == '12.0.1' }}
       shell: bash
       run: |
         version=${RELEASE##llvm-project-}; version=${version%.src}
         curl -LO https://github.com/llvm/llvm-project/releases/download/llvmorg-${version}/${{ matrix.release }}.tar.xz
-
     - name: Unpack llvm-project
-      if: ${{ matrix.clang-version < 9 }}
       shell: bash
       run: |
-        version=${RELEASE##llvm-project-}
-        tar xf llvm-${version}.src.tar.xz
-        tar xf cfe-${version}.src.tar.xz ${{ matrix.extra-tar-args-cfe }}
-        tar xf clang-tools-extra-${version}.src.tar.xz
-        mkdir ${{ matrix.release }}
-        mv llvm-${version}.src ${{ matrix.release }}/llvm
-        mv cfe-${version}.src ${{ matrix.release }}/clang
-        mv clang-tools-extra-${version}.src ${{ matrix.release }}/clang-tools-extra
-    - name: Unpack llvm-project
-      if: ${{ matrix.clang-version >= 9 || matrix.clang-version == '12.0.1' }}
-      shell: bash
-      run: |
-        tar xf ${{ matrix.release }}.tar.xz ${{ matrix.extra-tar-args }}
-    - name: Patch clang-8 includes
-      if: ${{ matrix.clang-version == 8 }}
-      shell: bash
-      run: patch ${{ matrix.release }}/llvm/include/llvm/Demangle/MicrosoftDemangleNodes.h include-cstdint-string-prior-to-using-uint8_t.patch
+        # ignore failure on v21 on windows
+        tar xf ${{ matrix.release }}.tar.xz ${{ matrix.extra-tar-args }} || true
     - name: Patch trivially-copyable clang 9/10
       if: ${{ ( matrix.clang-version == 9 || matrix.clang-version == 10 ) && matrix.os == 'windows' }}
       shell: bash
